# =============================================================================
# FastAPI Learning Server — server.py
# =============================================================================
# Run locally  : uvicorn server:app --reload --port 8000
# Run on AWS   : uvicorn server:app --host 0.0.0.0 --port 8000
#
# Interactive API docs (auto-generated by FastAPI):
#   http://localhost:8000/docs      ← Swagger UI  (try endpoints in browser)
#   http://localhost:8000/redoc     ← ReDoc UI    (cleaner read-only docs)
#
# Requirements:  pip install fastapi uvicorn python-multipart
# =============================================================================

# --- Core FastAPI imports -----------------------------------------------------
from fastapi import (
    FastAPI,          # The main application class
    HTTPException,    # Used to return error responses (404, 401, etc.)
    Depends,          # Dependency injection — lets us reuse logic (e.g. auth)
    Header,           # Lets us read HTTP request headers
    UploadFile,       # Represents an uploaded file from a multipart form
    File,             # Marker that tells FastAPI this param is an uploaded file
    WebSocket,        # WebSocket connection object
    WebSocketDisconnect,  # Exception raised when a client disconnects
    Request,          # Full HTTP request object (used in middleware)
    Response,         # Full HTTP response object (used in middleware)
    status,           # HTTP status code constants (e.g. status.HTTP_201_CREATED)
)

# --- Pydantic — data validation & schema models -------------------------------
# FastAPI uses Pydantic to validate request/response bodies automatically.
# If a client sends wrong types, FastAPI returns a 422 error automatically.
from pydantic import BaseModel, Field

# --- Standard library imports -------------------------------------------------
import time         # For measuring response duration in middleware
import uuid         # For generating unique IDs (tasks, files)
import io           # For wrapping bytes as a file-like object (in-memory files)
from datetime import datetime   # For timestamps on tasks and log entries

# --- FastAPI response helpers -------------------------------------------------
from fastapi.responses import StreamingResponse  # Stream file bytes to the client

# --- Typing helpers -----------------------------------------------------------
from typing import Optional, List  # For optional fields and typed lists

# =============================================================================
# APP INSTANCE
# =============================================================================
# FastAPI() creates the WSGI/ASGI application.
# title, description, version appear in /docs automatically.
app = FastAPI(
    title="FastAPI Learning Server",
    description="A playground API covering CRUD, Auth, File I/O, WebSockets, and Middleware.",
    version="1.0.0",
)


# =============================================================================
# IN-MEMORY "DATABASE"
# =============================================================================
# We use plain Python dicts instead of a real database so there is zero setup.
# WARNING: All data is lost when the server restarts — perfect for learning,
#          not for production.

# tasks_db  : { task_id (str) -> task dict }
tasks_db: dict = {}

# files_db  : { filename (str) -> {"content": bytes, "content_type": str} }
files_db: dict = {}

# request_log : list of dicts, one entry per request (filled by middleware)
request_log: list = []

# Valid API keys. In production you'd store hashed keys in a real database.
VALID_API_KEYS = {
    "dev-key-1234",   # key for development / learning
    "admin-key-9999", # key with admin label (same access here, but shows the pattern)
}


# =============================================================================
# MIDDLEWARE — runs on EVERY request, before and after your route handler
# =============================================================================
# @app.middleware("http") wraps every HTTP request.
# `call_next` calls the actual route function and returns its response.
@app.middleware("http")
async def logging_middleware(request: Request, call_next):
    """
    Logs method, URL, status code, and duration for every HTTP request.
    Middleware is the right place for cross-cutting concerns (logging, CORS,
    timing, rate limiting) because it runs regardless of which route is hit.
    """
    start_time = time.time()                 # Record start time

    response: Response = await call_next(request)  # Call the actual route

    duration_ms = round((time.time() - start_time) * 1000, 2)  # ms

    # Build a structured log entry
    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "method": request.method,             # GET / POST / PUT / DELETE / WS
        "path": str(request.url.path),        # e.g. /tasks/abc-123
        "status_code": response.status_code,  # 200, 201, 404, 401 …
        "duration_ms": duration_ms,
    }

    request_log.append(log_entry)            # Store in memory
    print(f"[LOG] {log_entry}")              # Also print to server console

    return response                          # Return the response to the client


# =============================================================================
# DEPENDENCY — API KEY AUTHENTICATION
# =============================================================================
# A "dependency" in FastAPI is a function that runs before your route handler.
# If it raises an HTTPException the route never executes — the error goes back
# to the client instead.  Use Depends(require_api_key) in any route you want
# to protect.

def require_api_key(x_api_key: str = Header(...)):
    """
    Reads the 'X-API-Key' header from the request.
    Header(...) means the header is REQUIRED — FastAPI returns 422 if missing.
    The header name 'x_api_key' (snake_case) maps to 'X-API-Key' (HTTP header).
    """
    if x_api_key not in VALID_API_KEYS:
        # 401 Unauthorized — the key was provided but it's wrong
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API key. Pass a valid key in the X-API-Key header.",
        )
    return x_api_key  # Return the key so the route can use it if needed


# =============================================================================
# PYDANTIC MODELS — define the shape of request and response bodies
# =============================================================================
# FastAPI reads these models to:
#   1. Validate incoming JSON automatically
#   2. Generate the /docs UI with correct field descriptions
#   3. Serialize outgoing Python dicts to JSON

class TaskCreate(BaseModel):
    """Body expected when CREATING a new task (POST /tasks)."""
    title: str = Field(..., min_length=1, max_length=200,
                       description="Short title for the task")
    description: Optional[str] = Field(None, description="Longer details (optional)")
    priority: int = Field(1, ge=1, le=5,
                          description="Priority 1 (low) to 5 (high)")


class TaskUpdate(BaseModel):
    """Body expected when UPDATING a task (PUT /tasks/{task_id}).
    All fields are Optional — client only sends what they want to change."""
    title: Optional[str] = Field(None, min_length=1, max_length=200)
    description: Optional[str] = None
    priority: Optional[int] = Field(None, ge=1, le=5)
    completed: Optional[bool] = None


class TaskResponse(BaseModel):
    """Shape of a task object returned to the client."""
    id: str
    title: str
    description: Optional[str]
    priority: int
    completed: bool
    created_at: str
    updated_at: str


# =============================================================================
# ROOT ROUTE
# =============================================================================

@app.get("/", tags=["Health"])
def root():
    """
    Health-check endpoint — no auth needed.
    Returns a simple message to confirm the server is alive.
    GET http://localhost:8000/
    """
    return {
        "message": "FastAPI Learning Server is running!",
        "docs": "/docs",
        "timestamp": datetime.utcnow().isoformat(),
    }


# =============================================================================
# TASKS — CRUD ENDPOINTS
# =============================================================================
# CRUD = Create, Read, Update, Delete
# Maps to HTTP methods: POST, GET, PUT, DELETE

# --- CREATE -------------------------------------------------------------------
@app.post(
    "/tasks",
    response_model=TaskResponse,          # FastAPI validates the return value against this model
    status_code=status.HTTP_201_CREATED,  # Return 201 (Created) instead of default 200
    tags=["Tasks"],
    dependencies=[Depends(require_api_key)],  # Auth required — runs before the function body
)
def create_task(task: TaskCreate):
    """
    Creates a new task and stores it in the in-memory DB.
    Client sends JSON body matching TaskCreate.
    FastAPI parses + validates it automatically before this function runs.
    """
    task_id = str(uuid.uuid4())  # Generate a unique ID (e.g. "3f2a1b...")
    now = datetime.utcnow().isoformat()

    # Build the full task dict to store
    new_task = {
        "id": task_id,
        "title": task.title,
        "description": task.description,
        "priority": task.priority,
        "completed": False,            # New tasks start incomplete
        "created_at": now,
        "updated_at": now,
    }

    tasks_db[task_id] = new_task       # Store in our dict "database"
    return new_task                    # FastAPI serializes this to JSON


# --- READ ALL -----------------------------------------------------------------
@app.get(
    "/tasks",
    response_model=List[TaskResponse],   # Returns a JSON array of TaskResponse objects
    tags=["Tasks"],
    dependencies=[Depends(require_api_key)],
)
def get_all_tasks(
    completed: Optional[bool] = None,    # Query param: /tasks?completed=true
    priority: Optional[int] = None,      # Query param: /tasks?priority=3
):
    """
    Returns all tasks. Supports optional filtering via query parameters.
    Query params are automatically read from the URL — no extra code needed.
    Example: GET /tasks?completed=false&priority=5
    """
    tasks = list(tasks_db.values())  # Get all tasks as a list

    # Filter by 'completed' if the query param was provided
    if completed is not None:
        tasks = [t for t in tasks if t["completed"] == completed]

    # Filter by 'priority' if the query param was provided
    if priority is not None:
        tasks = [t for t in tasks if t["priority"] == priority]

    return tasks  # FastAPI converts each dict to TaskResponse JSON


# --- READ ONE -----------------------------------------------------------------
@app.get(
    "/tasks/{task_id}",   # {task_id} is a PATH parameter — part of the URL itself
    response_model=TaskResponse,
    tags=["Tasks"],
    dependencies=[Depends(require_api_key)],
)
def get_task(task_id: str):
    """
    Returns a single task by its ID.
    Path parameters (task_id) are automatically extracted from the URL.
    Example: GET /tasks/3f2a1b-...
    """
    if task_id not in tasks_db:
        # 404 Not Found — standard when a resource doesn't exist
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task '{task_id}' not found.",
        )
    return tasks_db[task_id]


# --- UPDATE -------------------------------------------------------------------
@app.put(
    "/tasks/{task_id}",
    response_model=TaskResponse,
    tags=["Tasks"],
    dependencies=[Depends(require_api_key)],
)
def update_task(task_id: str, updates: TaskUpdate):
    """
    Partially updates an existing task (only fields provided in body are changed).
    This is sometimes called a PATCH-style update done via PUT.
    Client only needs to send the fields they want to change.
    """
    if task_id not in tasks_db:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task '{task_id}' not found.",
        )

    task = tasks_db[task_id]  # Get existing task from DB

    # .model_dump(exclude_unset=True) returns only the fields the client actually sent
    # So if client sends {"completed": true}, we only update 'completed' — nothing else
    incoming = updates.model_dump(exclude_unset=True)
    task.update(incoming)                         # Apply changes to the task dict
    task["updated_at"] = datetime.utcnow().isoformat()  # Refresh timestamp

    tasks_db[task_id] = task  # Save updated task back to DB
    return task


# --- DELETE -------------------------------------------------------------------
@app.delete(
    "/tasks/{task_id}",
    status_code=status.HTTP_200_OK,
    tags=["Tasks"],
    dependencies=[Depends(require_api_key)],
)
def delete_task(task_id: str):
    """
    Deletes a task by ID. Returns a confirmation message.
    A 204 No Content is also common for DELETE, but 200 with a message is
    easier to work with when learning.
    """
    if task_id not in tasks_db:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task '{task_id}' not found.",
        )

    del tasks_db[task_id]  # Remove from dict
    return {"message": f"Task '{task_id}' deleted successfully."}


# =============================================================================
# FILE UPLOAD / DOWNLOAD
# =============================================================================

@app.post(
    "/files/upload",
    tags=["Files"],
    dependencies=[Depends(require_api_key)],
)
async def upload_file(file: UploadFile = File(...)):
    """
    Accepts a file via multipart/form-data and stores it in memory.
    'UploadFile' gives you async access to the file content + metadata.
    Client must send a 'multipart/form-data' POST with field name 'file'.
    """
    contents = await file.read()        # Read all file bytes asynchronously
    files_db[file.filename] = {
        "content": contents,            # Raw bytes stored in memory
        "content_type": file.content_type,  # e.g. "image/png", "text/plain"
        "size_bytes": len(contents),
        "uploaded_at": datetime.utcnow().isoformat(),
    }
    return {
        "message": f"File '{file.filename}' uploaded successfully.",
        "filename": file.filename,
        "size_bytes": len(contents),
        "content_type": file.content_type,
    }


@app.get(
    "/files/{filename}",
    tags=["Files"],
    dependencies=[Depends(require_api_key)],
)
def download_file(filename: str):
    """
    Returns the stored file as a binary stream.
    StreamingResponse sends bytes directly — works for any file type.
    Client receives the raw file (images, PDFs, text, etc.)
    """
    if filename not in files_db:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"File '{filename}' not found.",
        )

    file_data = files_db[filename]

    # io.BytesIO wraps raw bytes as a file-like stream that StreamingResponse needs
    return StreamingResponse(
        io.BytesIO(file_data["content"]),
        media_type=file_data["content_type"],
        headers={
            # This header tells the browser/client to download the file, not render it
            "Content-Disposition": f'attachment; filename="{filename}"'
        },
    )


@app.get(
    "/files",
    tags=["Files"],
    dependencies=[Depends(require_api_key)],
)
def list_files():
    """Lists all uploaded files (name, size, type, timestamp). No content returned."""
    return [
        {
            "filename": name,
            "size_bytes": meta["size_bytes"],
            "content_type": meta["content_type"],
            "uploaded_at": meta["uploaded_at"],
        }
        for name, meta in files_db.items()
    ]


# =============================================================================
# REQUEST LOG VIEWER
# =============================================================================

@app.get(
    "/logs",
    tags=["Monitoring"],
    dependencies=[Depends(require_api_key)],
)
def get_logs(last_n: int = 20):
    """
    Returns the last N request log entries captured by the middleware.
    Use this to see every request the server has received since startup.
    Query param: /logs?last_n=50
    """
    return {
        "total_requests": len(request_log),
        "showing": min(last_n, len(request_log)),
        "logs": request_log[-last_n:],  # Python list slicing — last N items
    }


# =============================================================================
# WEBSOCKET — REAL-TIME CHAT ROOM
# =============================================================================
# WebSockets keep a persistent two-way connection open between client and server.
# Unlike HTTP (request → response → close), WebSockets stay open until
# either side closes them.

# ConnectionManager handles the list of active clients and broadcasts messages.
class ConnectionManager:
    def __init__(self):
        # List of all currently connected WebSocket objects
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket, username: str):
        """Accept the WebSocket handshake and add the client to the list."""
        await websocket.accept()                    # Complete the WS handshake
        self.active_connections.append(websocket)
        # Announce to everyone that a new user joined
        await self.broadcast(f"[Server] '{username}' joined the chat.", sender=None)

    def disconnect(self, websocket: WebSocket, username: str):
        """Remove the client from the active list (called on disconnect)."""
        self.active_connections.remove(websocket)

    async def broadcast(self, message: str, sender: WebSocket = None):
        """Send a message to ALL connected clients."""
        for connection in self.active_connections:
            await connection.send_text(message)    # send_text sends a UTF-8 string frame


# Single shared manager instance — all WebSocket routes share this
manager = ConnectionManager()


@app.websocket("/ws/chat/{username}")
async def websocket_chat(websocket: WebSocket, username: str):
    """
    WebSocket endpoint for multi-user chat.
    Connect with: ws://localhost:8000/ws/chat/YourName

    Flow:
    1. Client connects → server accepts and announces their arrival
    2. Client sends a text message → server broadcasts it to everyone
    3. Client disconnects → server removes them and announces departure
    """
    await manager.connect(websocket, username)  # Accept + announce

    try:
        while True:  # Keep listening for messages until client disconnects
            data = await websocket.receive_text()  # Wait for next message from this client

            # Prefix the message with the sender's username and timestamp
            timestamp = datetime.utcnow().strftime("%H:%M:%S")
            full_message = f"[{timestamp}] {username}: {data}"

            # Broadcast to all connected clients (including the sender)
            await manager.broadcast(full_message, sender=websocket)

    except WebSocketDisconnect:
        # This exception is raised automatically when the client closes the connection
        manager.disconnect(websocket, username)
        await manager.broadcast(f"[Server] '{username}' left the chat.", sender=None)


# =============================================================================
# WEBSOCKET STATUS — how many clients are connected right now
# =============================================================================

@app.get("/ws/status", tags=["WebSocket"])
def websocket_status():
    """Returns the number of currently connected WebSocket clients."""
    return {
        "connected_clients": len(manager.active_connections),
    }


# =============================================================================
# ENTRY POINT — run directly with: python server.py
# =============================================================================
# When deploying to AWS (EC2, App Runner, etc.) you typically use:
#   uvicorn server:app --host 0.0.0.0 --port 8000
# The --host 0.0.0.0 makes the server listen on all network interfaces,
# not just localhost — required for external connections.

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "server:app",   # "filename:FastAPI_instance_name"
        host="0.0.0.0", # Listen on all interfaces (needed for AWS)
        port=8000,
        reload=True,    # Auto-reload when you save the file (dev only)
    )
